load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "stemmadb",
    srcs = ["src/lib.rs"],
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        "//third_party/sqlite_vec",
        "@crates//:anyhow",
        "@crates//:rusqlite",
        "@crates//:thiserror",
        "@crates//:tracing",
    ],
)

rust_test(
    name = "stemmadb_test",
    crate = ":stemmadb",
)
