# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stemma/v1/embedder.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'stemma/v1/embedder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18stemma/v1/embedder.proto\x12\tstemma.v1\"\x1d\n\x0c\x45mbedRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"9\n\rEmbedResponse\x12(\n\nembeddings\x18\x01 \x03(\x0b\x32\x14.stemma.v1.Embedding\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\"0\n\rRerankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x10\n\x08passages\x18\x02 \x03(\t\" \n\x0eRerankResponse\x12\x0e\n\x06scores\x18\x01 \x03(\x01\"\x12\n\x10ModelInfoRequest\"X\n\x11ModelInfoResponse\x12\x0f\n\x07\x62\x61\x63kend\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x10\n\x08revision\x18\x03 \x01(\t\x12\x11\n\tdimension\x18\x04 \x01(\r2\xd4\x01\n\x0f\x45mbedderService\x12:\n\x05\x45mbed\x12\x17.stemma.v1.EmbedRequest\x1a\x18.stemma.v1.EmbedResponse\x12=\n\x06Rerank\x12\x18.stemma.v1.RerankRequest\x1a\x19.stemma.v1.RerankResponse\x12\x46\n\tModelInfo\x12\x1b.stemma.v1.ModelInfoRequest\x1a\x1c.stemma.v1.ModelInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stemma.v1.embedder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDREQUEST']._serialized_start=39
  _globals['_EMBEDREQUEST']._serialized_end=68
  _globals['_EMBEDRESPONSE']._serialized_start=70
  _globals['_EMBEDRESPONSE']._serialized_end=127
  _globals['_EMBEDDING']._serialized_start=129
  _globals['_EMBEDDING']._serialized_end=156
  _globals['_RERANKREQUEST']._serialized_start=158
  _globals['_RERANKREQUEST']._serialized_end=206
  _globals['_RERANKRESPONSE']._serialized_start=208
  _globals['_RERANKRESPONSE']._serialized_end=240
  _globals['_MODELINFOREQUEST']._serialized_start=242
  _globals['_MODELINFOREQUEST']._serialized_end=260
  _globals['_MODELINFORESPONSE']._serialized_start=262
  _globals['_MODELINFORESPONSE']._serialized_end=350
  _globals['_EMBEDDERSERVICE']._serialized_start=353
  _globals['_EMBEDDERSERVICE']._serialized_end=565
# @@protoc_insertion_point(module_scope)
