# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from stemma.v1 import embedder_pb2 as stemma_dot_v1_dot_embedder__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stemma/v1/embedder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbedderServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/stemma.v1.EmbedderService/Embed',
                request_serializer=stemma_dot_v1_dot_embedder__pb2.EmbedRequest.SerializeToString,
                response_deserializer=stemma_dot_v1_dot_embedder__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.Rerank = channel.unary_unary(
                '/stemma.v1.EmbedderService/Rerank',
                request_serializer=stemma_dot_v1_dot_embedder__pb2.RerankRequest.SerializeToString,
                response_deserializer=stemma_dot_v1_dot_embedder__pb2.RerankResponse.FromString,
                _registered_method=True)
        self.ModelInfo = channel.unary_unary(
                '/stemma.v1.EmbedderService/ModelInfo',
                request_serializer=stemma_dot_v1_dot_embedder__pb2.ModelInfoRequest.SerializeToString,
                response_deserializer=stemma_dot_v1_dot_embedder__pb2.ModelInfoResponse.FromString,
                _registered_method=True)


class EmbedderServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rerank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbedderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=stemma_dot_v1_dot_embedder__pb2.EmbedRequest.FromString,
                    response_serializer=stemma_dot_v1_dot_embedder__pb2.EmbedResponse.SerializeToString,
            ),
            'Rerank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rerank,
                    request_deserializer=stemma_dot_v1_dot_embedder__pb2.RerankRequest.FromString,
                    response_serializer=stemma_dot_v1_dot_embedder__pb2.RerankResponse.SerializeToString,
            ),
            'ModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.ModelInfo,
                    request_deserializer=stemma_dot_v1_dot_embedder__pb2.ModelInfoRequest.FromString,
                    response_serializer=stemma_dot_v1_dot_embedder__pb2.ModelInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stemma.v1.EmbedderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stemma.v1.EmbedderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbedderService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stemma.v1.EmbedderService/Embed',
            stemma_dot_v1_dot_embedder__pb2.EmbedRequest.SerializeToString,
            stemma_dot_v1_dot_embedder__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stemma.v1.EmbedderService/Rerank',
            stemma_dot_v1_dot_embedder__pb2.RerankRequest.SerializeToString,
            stemma_dot_v1_dot_embedder__pb2.RerankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stemma.v1.EmbedderService/ModelInfo',
            stemma_dot_v1_dot_embedder__pb2.ModelInfoRequest.SerializeToString,
            stemma_dot_v1_dot_embedder__pb2.ModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
