# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from stemma.v1 import resolve_pb2 as stemma_dot_v1_dot_resolve__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stemma/v1/resolve_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResolveServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Resolve = channel.unary_unary(
                '/stemma.v1.ResolveService/Resolve',
                request_serializer=stemma_dot_v1_dot_resolve__pb2.ResolveRequest.SerializeToString,
                response_deserializer=stemma_dot_v1_dot_resolve__pb2.ResolveResponse.FromString,
                _registered_method=True)
        self.Explain = channel.unary_unary(
                '/stemma.v1.ResolveService/Explain',
                request_serializer=stemma_dot_v1_dot_resolve__pb2.ResolveRequest.SerializeToString,
                response_deserializer=stemma_dot_v1_dot_resolve__pb2.ExplainResponse.FromString,
                _registered_method=True)
        self.Parse = channel.unary_unary(
                '/stemma.v1.ResolveService/Parse',
                request_serializer=stemma_dot_v1_dot_resolve__pb2.ParseRequest.SerializeToString,
                response_deserializer=stemma_dot_v1_dot_resolve__pb2.ParseResponse.FromString,
                _registered_method=True)
        self.SubmitFeedback = channel.unary_unary(
                '/stemma.v1.ResolveService/SubmitFeedback',
                request_serializer=stemma_dot_v1_dot_resolve__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=stemma_dot_v1_dot_resolve__pb2.Feedback.FromString,
                _registered_method=True)
        self.ListFeedback = channel.unary_unary(
                '/stemma.v1.ResolveService/ListFeedback',
                request_serializer=stemma_dot_v1_dot_resolve__pb2.ListFeedbackRequest.SerializeToString,
                response_deserializer=stemma_dot_v1_dot_resolve__pb2.FeedbackList.FromString,
                _registered_method=True)
        self.DeleteFeedback = channel.unary_unary(
                '/stemma.v1.ResolveService/DeleteFeedback',
                request_serializer=stemma_dot_v1_dot_resolve__pb2.DeleteFeedbackRequest.SerializeToString,
                response_deserializer=stemma_dot_v1_dot_resolve__pb2.DeleteFeedbackResponse.FromString,
                _registered_method=True)


class ResolveServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Resolve(self, request, context):
        """Resolve the entity mentions in a natural-language query against the
        database identified by `database`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Explain(self, request, context):
        """Like Resolve, but returns the full resolution trajectory: every span
        considered, every candidate from every channel with its scores, and the
        reason each near-miss was not selected. The analogue of SQL EXPLAIN;
        drives the UI's query-plan view.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Parse(self, request, context):
        """Resolve the query and propose a validated, parameterized read-only query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitFeedback(self, request, context):
        """Record an explicit judgment about one exact resolution or parse episode.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFeedback(self, request, context):
        """Retrieve explicit judgments for inspection or deletion.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFeedback(self, request, context):
        """Permanently remove one explicit judgment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResolveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=stemma_dot_v1_dot_resolve__pb2.ResolveRequest.FromString,
                    response_serializer=stemma_dot_v1_dot_resolve__pb2.ResolveResponse.SerializeToString,
            ),
            'Explain': grpc.unary_unary_rpc_method_handler(
                    servicer.Explain,
                    request_deserializer=stemma_dot_v1_dot_resolve__pb2.ResolveRequest.FromString,
                    response_serializer=stemma_dot_v1_dot_resolve__pb2.ExplainResponse.SerializeToString,
            ),
            'Parse': grpc.unary_unary_rpc_method_handler(
                    servicer.Parse,
                    request_deserializer=stemma_dot_v1_dot_resolve__pb2.ParseRequest.FromString,
                    response_serializer=stemma_dot_v1_dot_resolve__pb2.ParseResponse.SerializeToString,
            ),
            'SubmitFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitFeedback,
                    request_deserializer=stemma_dot_v1_dot_resolve__pb2.FeedbackRequest.FromString,
                    response_serializer=stemma_dot_v1_dot_resolve__pb2.Feedback.SerializeToString,
            ),
            'ListFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFeedback,
                    request_deserializer=stemma_dot_v1_dot_resolve__pb2.ListFeedbackRequest.FromString,
                    response_serializer=stemma_dot_v1_dot_resolve__pb2.FeedbackList.SerializeToString,
            ),
            'DeleteFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFeedback,
                    request_deserializer=stemma_dot_v1_dot_resolve__pb2.DeleteFeedbackRequest.FromString,
                    response_serializer=stemma_dot_v1_dot_resolve__pb2.DeleteFeedbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stemma.v1.ResolveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stemma.v1.ResolveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResolveService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stemma.v1.ResolveService/Resolve',
            stemma_dot_v1_dot_resolve__pb2.ResolveRequest.SerializeToString,
            stemma_dot_v1_dot_resolve__pb2.ResolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Explain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stemma.v1.ResolveService/Explain',
            stemma_dot_v1_dot_resolve__pb2.ResolveRequest.SerializeToString,
            stemma_dot_v1_dot_resolve__pb2.ExplainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Parse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stemma.v1.ResolveService/Parse',
            stemma_dot_v1_dot_resolve__pb2.ParseRequest.SerializeToString,
            stemma_dot_v1_dot_resolve__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stemma.v1.ResolveService/SubmitFeedback',
            stemma_dot_v1_dot_resolve__pb2.FeedbackRequest.SerializeToString,
            stemma_dot_v1_dot_resolve__pb2.Feedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stemma.v1.ResolveService/ListFeedback',
            stemma_dot_v1_dot_resolve__pb2.ListFeedbackRequest.SerializeToString,
            stemma_dot_v1_dot_resolve__pb2.FeedbackList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stemma.v1.ResolveService/DeleteFeedback',
            stemma_dot_v1_dot_resolve__pb2.DeleteFeedbackRequest.SerializeToString,
            stemma_dot_v1_dot_resolve__pb2.DeleteFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
